[pytorch]
repository = "https://github.com/pytorch/pytorch.git"
ref = "cf30153c4c131c8164ee7798e5022d810682e2cb"
version = "2.13.0+pyodide314.0.2"

[pyodide]
version = "314.0.2"
build_version = "0.36.0"
python_version = "3.14.2"
python_tag = "cp314"
emscripten_version = "5.0.3"
platform_tag = "pyemscripten_2026_0_wasm32"

[release]
tag = "torch-2.13.0-pyodide-314.0.2-r1"

[build]
max_jobs = 3
maximum_wheel_mib = 80

[host_tools]
wheel_version = "0.47.0"
ninja_version = "1.13.0"
cmake_version = "3.27.9"
